[package]
name = "sire"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
dirs = "5.0.1"
clap = { version = "4.5.20", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v4", "fast-rng"] }
