[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.11.0", features = ["v4", "fast-rng"] }
dirs = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
